namespace Project.ValueTypes
{

    #region Dungeon Generation

    /// <summary>
    /// Designates the dungeon generation algorithm to use
    /// </summary>
    public enum DungeonPatternType : byte
    {
        OneRoom = 0,
        OneRoomDark = 1,
        StandardRandom = 2,
        StandardRandomDoubleCorridors = 3,
        Random = 254,    //Chooses one of the algorithms above randomly
    }

    /// <summary>
    /// Designates the type of the Feature generated by the DungeonGenerator (room, corridor, etc.)
    /// </summary>
    public enum FeatureType : byte
    {
        Room = 0,
        Corridor = 1,
    }
    #endregion


    #region Behaviours

    public enum FOVPatternType : byte
    {
        Square = 0,
        Circle = 1,
    }

    public enum MovementPatternType : byte
    {
        Input = 0,   //Uses the Player's inputs
        Random = 1,  //The next adjacent Tile is chosen at random
        Explore = 2, //Finds the closest unexplored Floor Tile until none are found or an enemy is nearby
    }

    #endregion
}