namespace Project.ValueTypes
{

    #region Dungeon Generation

    /// <summary>
    /// Designates the dungeon generation algorithm to use
    /// </summary>
    public enum DungeonPatternType : byte
    {
        OneRoom = 0,
        OneRoomDark = 1,
        StandardRandom = 2,
        StandardRandomDoubleCorridors = 3,
        Random = 254,    //Chooses one of the algorithms above randomly
    }

    /// <summary>
    /// Designates the type of the Feature generated by the DungeonGenerator (room, corridor, etc.)
    /// </summary>
    public enum FeatureType : byte
    {
        Room = 0,
        Corridor = 1,
    }

    /// <summary>
    /// Designates the orientation of the object relative to the world (ex: Walls from Features)
    /// </summary>
    public enum PolarDirection : byte
    {
        North = 0,
        NorthEast = 1,
        East = 2,
        SouthEast = 3,
        South = 4,
        SouthWest = 5,
        West = 6,
        NorthWest = 7
    }

    #endregion


    #region Behaviours

    public enum FOVPatternType : byte
    {
        Square = 0,
    }

    #endregion
}